- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  vars:
    # formulaの追加
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
    # formuraのインストール
    homebrew_packages:
      # RubyとPHPの使用準備 (anyenvのrbenv, phpenvで管理)
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: re2c }
      - { name: jpeg }
      - { name: libpng }
      - { name: libmcrypt }
      # 必要なソフト
      - { name: mysql }
      - { name: imagemagick }
      # 便利アイテム達
      - { name: git }
      - { name: zsh, install_options: disable-etcdir }
      - { name: wget }
      - { name: vim }
      - { name: screen }
      - { name: nkf }
    # Appのインストール
    homebrew_cask_packages:
      - { name: dropbox }
      - { name: java }
      - { name: flux }
      - { name: google-japanese-ime }

  tasks:
    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew tap
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    # brew install
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # brew cask install
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # anyenvでrbenvとphpenvを導入
    - name: Install rbenv & phpenv with anyenv
      shell: git clone https://github.com/riywo/anyenv ~/.anyenv && exec $SHELL -l && anyenv install rbenv && anyenv install phpenv && exec $SHELL -l
    - name: Install gem packages
      sudo: yes
      gem: name={{ item.name }} state={{ item.state }} user_install=no
      with_items:
          - {name: "rake", state: "present"}
          - {name: "serverspec", state: "present"}
